name = input ('What is your name?')
print (f"Hello {name} and welcome to Ct8")
print ("Today we will tell a story with your help")
print ("")
print ("")
animal = input ("Pick an animal")
location = input ("Now pick a location")
print ("---------------------------------------")
print (f"One day, a {animal} wandered into the {location} ...")
print ("----------------------------------------")
past_tense_action = input ("Now pick a past tense action")
print ("----------------------------------------")
print (f"One day, a {animal} wandered into the {location} and they {past_tense_action} ...")
print ("----------------------------------------")
food = input ("Now pick a food")
print (f"One day, a {animal} wandered into the {location} and they {past_tense_action}. Then they got hungry and decided to eat a {food}.")
print ("THE ENDDD!!!!!")